[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16" }


[[redirects]]
  from = "https://:url/cloudinaried/:height/:image"
  to = "https://res.cloudinary.com/philhawksworth/image/fetch/q_auto,f_auto,h_:height/https://:url/images/:image"
  status = 200


[[redirects]]
  from = "/cloudinaried/:height/:image"
  to = "/images/:image"
  status = 404
